# Generated by Django 3.1.13 on 2021-11-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popokemon',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
